config/routes.rb
Rails.application.routes.draw do
  get    'signup', to: 'users#new'

  get  'messages', to: 'messages#index'
  get 'send_message', to: 'messages#new'
  
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'

  delete '/logout',  to: 'sessions#destroy'
  resources :users
  resources :messages
  resources :friend_lists  
  get 'welcome/index'
  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friend_list.rb
class FriendList < ApplicationRecord
end

app/models/friendlist.rb
class Friendlist < ApplicationRecord
end

app/models/message.rb
class Message < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/friend_lists_controller.rb
class FriendListsController < ApplicationController
    def create
        @friendlist = FriendList.new(friend_list_params)
        if @friendlist.save
          flash[:success] = "Add friend success!"
          redirect_to users_path
        else
          render 'new'
        end
    end
    private  
    def friend_list_params
      params.require(:friend_list).permit(:friend_id, :user_id)
    end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
    
    # show all receive message
    def index
        @inMessages =Message.where(receiver_id: current_user.id)   
        @outMessages =Message.where(sender_id: current_user.id)   
    end
    def new  
        @message = Message.new      
        @friendlist = friend_list
    end
    def create
        @message = Message.new(message_params)
        if @message.save
            flash[:success] = "Send successfully"
            redirect_to messages_path
        else
           render 'new'
        end
    end
    # change status of message
    def setReaded(id)
        Message.update(id, :status=>1, :seen_time => Time.new)
    end
    # destroy message have been seen
    private
        def message_params
            params.require(:message).permit(:receiver_id,:content,:seen_time).merge!({sender_id: current_user.id, status: 0 })
        end
   
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to messages_path
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end
  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
  def index
    @users = User.where.not(id: current_user.id)
    @friendlist =  FriendList.new
    @message= Message.new
  end
  def new
    @user = User.new
  end
  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Welcome to the My App!"
      redirect_to @user
    else
      render 'new'
    end
  end
  private  
      def user_params
        params.require(:user).permit(:name, :email, :password,
                                     :password_confirmation)
      end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friend_lists_helper.rb
module FriendListsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
     # change status of message
     def setReaded(id)
        Message.update(id, :status=>1, :seen_time => Time.new)
    end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end
  # Returns the current logged-in user (if any).
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  # return the friend_list of current_user
  def friend_list    
    if(current_user)
      @friend_list ||= FriendList.find_by(user_id: @current_user.id)
    end
  end 
  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end
    # Logs out the current user.
    def log_out
      session.delete(:user_id)
      @current_user = nil
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag 'icons/paper-plane.svg' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  </head>

  <body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <%= link_to (image_tag "icons/paper-plane.svg",size: "30x30",class: "d-inline-block align-top"), root_path, class:"navbar-brand"  %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
    <% if logged_in? %> 
    <li class="nav-item">
      <%= active_link_to 'Users', users_path, class:"nav-link" %>
      </li>
      <li class="nav-item">
      <%= active_link_to "Messages", messages_path, class:"nav-link" %>
      </li>
      <% end %>
    </ul>
    <div class="mx-sm-3">
    <% if logged_in? %>
    <%= link_to "Log out", logout_path,class:"btn btn-outline-light",role:"button", method: :delete %>
    <%= link_to "Send Message", send_message_path, class: "btn btn-success",role:"button" %>      
    <% else %>
   <%= link_to "Login", login_path, class:"btn btn-outline-light" ,role:"button" %>
   <%= link_to "Sign up", signup_path, class:"btn btn-outline-light" ,role: "button"  %>
    
   <% end %>
   </div>
  </div>

</nav>
<% flash.each do |message_type, message| %>


<% end %>

    <%= yield %>
  </body>
</html>

app/views/messages/_message.html.erb
    <div class="col-sm">
    <div class="card" data-id="<%= message.id %>">
      <div class="card-body">
        <h4 class="card-title"><%= message.sender_id %></h4>
        <p class="card-text"><%= message.content %></p>
      </div>
    </div>
    </div>

app/views/messages/index.html.erb
<div class="container">

  <h1>Inbox</h1>
  <% @inMessages.each do |message| %>
    <% if message.status == 0 %>
      <div class="col-sm">
        <div class="card">
          <div class="card-body">

            <h4 class="card-title">
              <b>Sender:</b>
              <%= message.sender_id %>
            </h4>
            <%= link_to 'See more', '#',
              :onclick => setReaded(message.id)%>
              <p class="card-text content-message">
                <b>Sent at:</b>
                <%= message.created_at %>
              </p>
              <div id="message-content">
                <p class="card-text content-message">
                  <b>Message:</b>
                  <%= message.content %>
                </p>
              </div>
          </div>
        </div>
      </div>
      <% end %>
        <% end %>

          <h1>Sent</h1>
          <% @outMessages.each do |message| %>
            <div class="col-sm">
              <div class="card">
                <div class="card-body">
                  <h4 class="card-title">
                    <%= message.receiver_id %>
                  </h4>
                  <p class="card-text">
                    <%= message.content %>
                  </p>
                  <% if message.status == 0%>
                    <span class="label label-danger">Unread</span>
                    <% else %>
                      Read at:
                      <%= message.seen_time%>
                        <% end %>
                </div>
              </div>
            </div>
            <% end %>

app/views/messages/index.js.erb
$('.container').append('<%= escape_javascript(render(:partial => @message)) %>')

app/views/messages/new.html.erb
<div class="container">
    <div class="row justify-content-center">
                <%= form_for(@message) do |f|%>        
                <h1>Message</h1>                
                <%= f.label :receiver_id %>
                <%= f.text_field :receiver_id, class:"form-control" %>
                
                <%= f.label :content %>
                <%= f.text_field :content, class:"form-control" %>
                <%= f.submit "Send", class:"btn btn-primary form-control"%>
                <% end %>                
            
    </div>
</div>

app/views/users/index.html.erb
<div class="container">
  <h1>Listing users</h1>
  <% @users.each do |user| %>
    <div class="col-sm">
      <%= form_for (@friendlist) do |f| %>
        <div class="card">
          <div class="card-body">
            <h4 class="card-title">
              <%= user.name %>
            </h4>
            <p class="card-text">
              <%= user.email %>
            </p>
            <%= f.hidden_field :friend_id, :value => user.id%>
              <%= f.hidden_field :user_id, :value => current_user.id%>
                <%= f.hidden_field :status, :value => 0%>
                  <%= f.submit "Add Friend", class:"btn btn-primary form-control" %>
          </div>
        </div>
        <% end %>
    </div>
    <% end %> 
</div>

app/views/users/new.html.erb
<div class="container">

<div class="row justify-content-center">


<%= form_for (@user) do |f| %>
  <h1>Signup!</h1>
  <%= f.label :name %>
  <%= f.text_field :name, class:"form-control" %>
  <%= f.label :email %>
  <%= f.text_field :email, class:"form-control" %>
  <%= f.label :password %>
  <%= f.password_field :password, class:"form-control" %>
  <%= f.label :password_confirmation,"Confirmation" %>
  <%= f.password_field :password_confirmation, class:"form-control" %>
  <%= f.submit "Create my account", class:"btn btn-primary form-control" %>

<% end %>
</div>
</div>

app/views/users/show.html.erb
<%= @user.name %>, <%= @user.email %>